// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type AcceptTransactionBadRequest Error

func (*AcceptTransactionBadRequest) acceptTransactionRes() {}

type AcceptTransactionInternalServerError Error

func (*AcceptTransactionInternalServerError) acceptTransactionRes() {}

// AcceptTransactionNoContent is response for AcceptTransaction operation.
type AcceptTransactionNoContent struct{}

func (*AcceptTransactionNoContent) acceptTransactionRes() {}

type AcceptTransactionNotFound Error

func (*AcceptTransactionNotFound) acceptTransactionRes() {}

// Ref: #/components/schemas/Balance
type Balance struct {
	Balance int64 `json:"balance"`
}

// GetBalance returns the value of Balance.
func (s *Balance) GetBalance() int64 {
	return s.Balance
}

// SetBalance sets the value of Balance.
func (s *Balance) SetBalance(val int64) {
	s.Balance = val
}

func (*Balance) getUserBalanceByIdRes()    {}
func (*Balance) updateUserBalanceByIdRes() {}

type CancelTransactionBadRequest Error

func (*CancelTransactionBadRequest) cancelTransactionRes() {}

type CancelTransactionInternalServerError Error

func (*CancelTransactionInternalServerError) cancelTransactionRes() {}

// CancelTransactionNoContent is response for CancelTransaction operation.
type CancelTransactionNoContent struct{}

func (*CancelTransactionNoContent) cancelTransactionRes() {}

type CancelTransactionNotFound Error

func (*CancelTransactionNotFound) cancelTransactionRes() {}

type ClaimDailyBalanceBadRequest Error

func (*ClaimDailyBalanceBadRequest) claimDailyBalanceRes() {}

type ClaimDailyBalanceConflict Error

func (*ClaimDailyBalanceConflict) claimDailyBalanceRes() {}

type ClaimDailyBalanceForbidden Error

func (*ClaimDailyBalanceForbidden) claimDailyBalanceRes() {}

type ClaimDailyBalanceInternalServerError Error

func (*ClaimDailyBalanceInternalServerError) claimDailyBalanceRes() {}

// ClaimDailyBalanceNoContent is response for ClaimDailyBalance operation.
type ClaimDailyBalanceNoContent struct{}

func (*ClaimDailyBalanceNoContent) claimDailyBalanceRes() {}

type ClaimDailyBalanceNotFound Error

func (*ClaimDailyBalanceNotFound) claimDailyBalanceRes() {}

type ClaimDailyBalanceUnauthorized Error

func (*ClaimDailyBalanceUnauthorized) claimDailyBalanceRes() {}

type CreateDiscordUserBadRequest Error

func (*CreateDiscordUserBadRequest) createDiscordUserRes() {}

type CreateDiscordUserConflict Error

func (*CreateDiscordUserConflict) createDiscordUserRes() {}

// Merged schema.
// Ref: #/components/schemas/CreateDiscordUserData
type CreateDiscordUserData struct {
	DiscordId string `json:"discordId"`
	Password  string `json:"password"`
}

// GetDiscordId returns the value of DiscordId.
func (s *CreateDiscordUserData) GetDiscordId() string {
	return s.DiscordId
}

// GetPassword returns the value of Password.
func (s *CreateDiscordUserData) GetPassword() string {
	return s.Password
}

// SetDiscordId sets the value of DiscordId.
func (s *CreateDiscordUserData) SetDiscordId(val string) {
	s.DiscordId = val
}

// SetPassword sets the value of Password.
func (s *CreateDiscordUserData) SetPassword(val string) {
	s.Password = val
}

type CreateDiscordUserInternalServerError Error

func (*CreateDiscordUserInternalServerError) createDiscordUserRes() {}

type CreateLinkAccountCodeBadRequest Error

func (*CreateLinkAccountCodeBadRequest) createLinkAccountCodeRes() {}

type CreateLinkAccountCodeInternalServerError Error

func (*CreateLinkAccountCodeInternalServerError) createLinkAccountCodeRes() {}

type CreateLinkAccountCodeNotFound Error

func (*CreateLinkAccountCodeNotFound) createLinkAccountCodeRes() {}

// Ref: #/components/schemas/CreateTransaction
type CreateTransaction struct {
	SenderUsername   string                `json:"sender_username"`
	ReceiverUsername string                `json:"receiver_username"`
	Amount           float64               `json:"amount"`
	Type             CreateTransactionType `json:"type"`
}

// GetSenderUsername returns the value of SenderUsername.
func (s *CreateTransaction) GetSenderUsername() string {
	return s.SenderUsername
}

// GetReceiverUsername returns the value of ReceiverUsername.
func (s *CreateTransaction) GetReceiverUsername() string {
	return s.ReceiverUsername
}

// GetAmount returns the value of Amount.
func (s *CreateTransaction) GetAmount() float64 {
	return s.Amount
}

// GetType returns the value of Type.
func (s *CreateTransaction) GetType() CreateTransactionType {
	return s.Type
}

// SetSenderUsername sets the value of SenderUsername.
func (s *CreateTransaction) SetSenderUsername(val string) {
	s.SenderUsername = val
}

// SetReceiverUsername sets the value of ReceiverUsername.
func (s *CreateTransaction) SetReceiverUsername(val string) {
	s.ReceiverUsername = val
}

// SetAmount sets the value of Amount.
func (s *CreateTransaction) SetAmount(val float64) {
	s.Amount = val
}

// SetType sets the value of Type.
func (s *CreateTransaction) SetType(val CreateTransactionType) {
	s.Type = val
}

type CreateTransactionBadRequest Error

func (*CreateTransactionBadRequest) createTransactionRes() {}

type CreateTransactionConflict Error

func (*CreateTransactionConflict) createTransactionRes() {}

type CreateTransactionInternalServerError Error

func (*CreateTransactionInternalServerError) createTransactionRes() {}

type CreateTransactionNotFound Error

func (*CreateTransactionNotFound) createTransactionRes() {}

type CreateTransactionType string

const (
	CreateTransactionTypeSend    CreateTransactionType = "send"
	CreateTransactionTypeRequest CreateTransactionType = "request"
)

// AllValues returns all CreateTransactionType values.
func (CreateTransactionType) AllValues() []CreateTransactionType {
	return []CreateTransactionType{
		CreateTransactionTypeSend,
		CreateTransactionTypeRequest,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateTransactionType) MarshalText() ([]byte, error) {
	switch s {
	case CreateTransactionTypeSend:
		return []byte(s), nil
	case CreateTransactionTypeRequest:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateTransactionType) UnmarshalText(data []byte) error {
	switch CreateTransactionType(data) {
	case CreateTransactionTypeSend:
		*s = CreateTransactionTypeSend
		return nil
	case CreateTransactionTypeRequest:
		*s = CreateTransactionTypeRequest
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateUserBadRequest Error

func (*CreateUserBadRequest) createUserRes() {}

type CreateUserConflict Error

func (*CreateUserConflict) createUserRes() {}

// Merged schema.
// Ref: #/components/schemas/CreateUserData
type CreateUserData struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	// User password.
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *CreateUserData) GetEmail() string {
	return s.Email
}

// GetUsername returns the value of Username.
func (s *CreateUserData) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *CreateUserData) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *CreateUserData) SetEmail(val string) {
	s.Email = val
}

// SetUsername sets the value of Username.
func (s *CreateUserData) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *CreateUserData) SetPassword(val string) {
	s.Password = val
}

type CreateUserInternalServerError Error

func (*CreateUserInternalServerError) createUserRes() {}

// Ref: #/components/schemas/DailyClaimStatus
type DailyClaimStatus struct {
	// Indicates if the user can claim their daily balance.
	CanClaim bool `json:"can_claim"`
}

// GetCanClaim returns the value of CanClaim.
func (s *DailyClaimStatus) GetCanClaim() bool {
	return s.CanClaim
}

// SetCanClaim sets the value of CanClaim.
func (s *DailyClaimStatus) SetCanClaim(val bool) {
	s.CanClaim = val
}

func (*DailyClaimStatus) getDailyClaimStatusRes() {}

// Merged schema.
// Ref: #/components/schemas/DiscordUser
type DiscordUser struct {
	ID        int    `json:"id"`
	DiscordId string `json:"discordId"`
}

// GetID returns the value of ID.
func (s *DiscordUser) GetID() int {
	return s.ID
}

// GetDiscordId returns the value of DiscordId.
func (s *DiscordUser) GetDiscordId() string {
	return s.DiscordId
}

// SetID sets the value of ID.
func (s *DiscordUser) SetID(val int) {
	s.ID = val
}

// SetDiscordId sets the value of DiscordId.
func (s *DiscordUser) SetDiscordId(val string) {
	s.DiscordId = val
}

func (*DiscordUser) createDiscordUserRes() {}

// Ref: #/components/schemas/DiscordUserAutofill
type DiscordUserAutofill struct {
	Autofill int `json:"autofill"`
}

// GetAutofill returns the value of Autofill.
func (s *DiscordUserAutofill) GetAutofill() int {
	return s.Autofill
}

// SetAutofill sets the value of Autofill.
func (s *DiscordUserAutofill) SetAutofill(val int) {
	s.Autofill = val
}

func (*DiscordUserAutofill) getDiscordUserAutofillByIdRes()    {}
func (*DiscordUserAutofill) updateDiscordUserAutofillByIdRes() {}

// Ref: #/components/schemas/DiscordUserLanguage
type DiscordUserLanguage struct {
	Language string `json:"language"`
}

// GetLanguage returns the value of Language.
func (s *DiscordUserLanguage) GetLanguage() string {
	return s.Language
}

// SetLanguage sets the value of Language.
func (s *DiscordUserLanguage) SetLanguage(val string) {
	s.Language = val
}

func (*DiscordUserLanguage) getDiscordUserLanguageByIdRes()    {}
func (*DiscordUserLanguage) updateDiscordUserLanguageByIdRes() {}

// Ref: #/components/schemas/DiscordUserLoginData
type DiscordUserLoginData struct {
	DiscordId string `json:"discordId"`
	Password  string `json:"password"`
}

// GetDiscordId returns the value of DiscordId.
func (s *DiscordUserLoginData) GetDiscordId() string {
	return s.DiscordId
}

// GetPassword returns the value of Password.
func (s *DiscordUserLoginData) GetPassword() string {
	return s.Password
}

// SetDiscordId sets the value of DiscordId.
func (s *DiscordUserLoginData) SetDiscordId(val string) {
	s.DiscordId = val
}

// SetPassword sets the value of Password.
func (s *DiscordUserLoginData) SetPassword(val string) {
	s.Password = val
}

// Merged schema.
// Ref: #/components/schemas/DiscordUserSessionData
type DiscordUserSessionData struct {
	DiscordId string `json:"discordId"`
	Autofill  int    `json:"autofill"`
	Language  string `json:"language"`
}

// GetDiscordId returns the value of DiscordId.
func (s *DiscordUserSessionData) GetDiscordId() string {
	return s.DiscordId
}

// GetAutofill returns the value of Autofill.
func (s *DiscordUserSessionData) GetAutofill() int {
	return s.Autofill
}

// GetLanguage returns the value of Language.
func (s *DiscordUserSessionData) GetLanguage() string {
	return s.Language
}

// SetDiscordId sets the value of DiscordId.
func (s *DiscordUserSessionData) SetDiscordId(val string) {
	s.DiscordId = val
}

// SetAutofill sets the value of Autofill.
func (s *DiscordUserSessionData) SetAutofill(val int) {
	s.Autofill = val
}

// SetLanguage sets the value of Language.
func (s *DiscordUserSessionData) SetLanguage(val string) {
	s.Language = val
}

func (*DiscordUserSessionData) loginDiscordUserRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Message OptString `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() OptString {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val OptString) {
	s.Message = val
}

type GetAccountLinkByIdBadRequest Error

func (*GetAccountLinkByIdBadRequest) getAccountLinkByIdRes() {}

type GetAccountLinkByIdConflict Error

func (*GetAccountLinkByIdConflict) getAccountLinkByIdRes() {}

type GetAccountLinkByIdInternalServerError Error

func (*GetAccountLinkByIdInternalServerError) getAccountLinkByIdRes() {}

type GetAccountLinkByIdNotFound Error

func (*GetAccountLinkByIdNotFound) getAccountLinkByIdRes() {}

type GetDailyClaimStatusBadRequest Error

func (*GetDailyClaimStatusBadRequest) getDailyClaimStatusRes() {}

type GetDailyClaimStatusForbidden Error

func (*GetDailyClaimStatusForbidden) getDailyClaimStatusRes() {}

type GetDailyClaimStatusInternalServerError Error

func (*GetDailyClaimStatusInternalServerError) getDailyClaimStatusRes() {}

type GetDailyClaimStatusNotFound Error

func (*GetDailyClaimStatusNotFound) getDailyClaimStatusRes() {}

type GetDailyClaimStatusUnauthorized Error

func (*GetDailyClaimStatusUnauthorized) getDailyClaimStatusRes() {}

type GetDiscordUserAutofillByIdBadRequest Error

func (*GetDiscordUserAutofillByIdBadRequest) getDiscordUserAutofillByIdRes() {}

type GetDiscordUserAutofillByIdInternalServerError Error

func (*GetDiscordUserAutofillByIdInternalServerError) getDiscordUserAutofillByIdRes() {}

type GetDiscordUserAutofillByIdNotFound Error

func (*GetDiscordUserAutofillByIdNotFound) getDiscordUserAutofillByIdRes() {}

type GetDiscordUserLanguageByIdBadRequest Error

func (*GetDiscordUserLanguageByIdBadRequest) getDiscordUserLanguageByIdRes() {}

type GetDiscordUserLanguageByIdInternalServerError Error

func (*GetDiscordUserLanguageByIdInternalServerError) getDiscordUserLanguageByIdRes() {}

type GetDiscordUserLanguageByIdNotFound Error

func (*GetDiscordUserLanguageByIdNotFound) getDiscordUserLanguageByIdRes() {}

type GetTransactionsBadRequest Error

func (*GetTransactionsBadRequest) getTransactionsRes() {}

type GetTransactionsInternalServerError Error

func (*GetTransactionsInternalServerError) getTransactionsRes() {}

type GetTransactionsNotFound Error

func (*GetTransactionsNotFound) getTransactionsRes() {}

type GetUserBalanceByIdBadRequest Error

func (*GetUserBalanceByIdBadRequest) getUserBalanceByIdRes() {}

type GetUserBalanceByIdForbidden Error

func (*GetUserBalanceByIdForbidden) getUserBalanceByIdRes() {}

type GetUserBalanceByIdInternalServerError Error

func (*GetUserBalanceByIdInternalServerError) getUserBalanceByIdRes() {}

type GetUserBalanceByIdNotFound Error

func (*GetUserBalanceByIdNotFound) getUserBalanceByIdRes() {}

type GetUserBalanceByIdUnauthorized Error

func (*GetUserBalanceByIdUnauthorized) getUserBalanceByIdRes() {}

type GetUserByIdBadRequest Error

func (*GetUserByIdBadRequest) getUserByIdRes() {}

type GetUserByIdForbidden Error

func (*GetUserByIdForbidden) getUserByIdRes() {}

type GetUserByIdInternalServerError Error

func (*GetUserByIdInternalServerError) getUserByIdRes() {}

type GetUserByIdNotFound Error

func (*GetUserByIdNotFound) getUserByIdRes() {}

type GetUserByIdUnauthorized Error

func (*GetUserByIdUnauthorized) getUserByIdRes() {}

type LinkAccountBadRequest Error

func (*LinkAccountBadRequest) linkAccountRes() {}

type LinkAccountConflict Error

func (*LinkAccountConflict) linkAccountRes() {}

type LinkAccountInternalServerError Error

func (*LinkAccountInternalServerError) linkAccountRes() {}

type LinkAccountNotFound Error

func (*LinkAccountNotFound) linkAccountRes() {}

// Ref: #/components/schemas/LinkCode
type LinkCode struct {
	Code string `json:"code"`
}

// GetCode returns the value of Code.
func (s *LinkCode) GetCode() string {
	return s.Code
}

// SetCode sets the value of Code.
func (s *LinkCode) SetCode(val string) {
	s.Code = val
}

func (*LinkCode) createLinkAccountCodeRes() {}

// Ref: #/components/schemas/LinkedAccountID
type LinkedAccountID struct {
	ID int `json:"id"`
}

// GetID returns the value of ID.
func (s *LinkedAccountID) GetID() int {
	return s.ID
}

// SetID sets the value of ID.
func (s *LinkedAccountID) SetID(val int) {
	s.ID = val
}

func (*LinkedAccountID) getAccountLinkByIdRes() {}
func (*LinkedAccountID) linkAccountRes()        {}

// Ref: #/components/schemas/LoginData
type LoginData struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *LoginData) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *LoginData) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *LoginData) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *LoginData) SetPassword(val string) {
	s.Password = val
}

type LoginDiscordUserBadRequest Error

func (*LoginDiscordUserBadRequest) loginDiscordUserRes() {}

type LoginDiscordUserInternalServerError Error

func (*LoginDiscordUserInternalServerError) loginDiscordUserRes() {}

type LoginDiscordUserNotFound Error

func (*LoginDiscordUserNotFound) loginDiscordUserRes() {}

type LoginDiscordUserUnauthorized Error

func (*LoginDiscordUserUnauthorized) loginDiscordUserRes() {}

type LoginUserBadRequest Error

func (*LoginUserBadRequest) loginUserRes() {}

type LoginUserInternalServerError Error

func (*LoginUserInternalServerError) loginUserRes() {}

type LoginUserNotFound Error

func (*LoginUserNotFound) loginUserRes() {}

type LoginUserUnauthorized Error

func (*LoginUserUnauthorized) loginUserRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type RefundTransactionBadRequest Error

func (*RefundTransactionBadRequest) refundTransactionRes() {}

type RefundTransactionInternalServerError Error

func (*RefundTransactionInternalServerError) refundTransactionRes() {}

// RefundTransactionNoContent is response for RefundTransaction operation.
type RefundTransactionNoContent struct{}

func (*RefundTransactionNoContent) refundTransactionRes() {}

type RefundTransactionNotFound Error

func (*RefundTransactionNotFound) refundTransactionRes() {}

type RejectTransactionBadRequest Error

func (*RejectTransactionBadRequest) rejectTransactionRes() {}

type RejectTransactionInternalServerError Error

func (*RejectTransactionInternalServerError) rejectTransactionRes() {}

// RejectTransactionNoContent is response for RejectTransaction operation.
type RejectTransactionNoContent struct{}

func (*RejectTransactionNoContent) rejectTransactionRes() {}

type RejectTransactionNotFound Error

func (*RejectTransactionNotFound) rejectTransactionRes() {}

// Ref: #/components/schemas/Token
type Token struct {
	Token string `json:"token"`
}

// GetToken returns the value of Token.
func (s *Token) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *Token) SetToken(val string) {
	s.Token = val
}

func (*Token) loginUserRes() {}

// Ref: #/components/schemas/Transaction
type Transaction struct {
	ID TransactionID `json:"id"`
	// Sender User ID.
	SenderID int `json:"sender_id"`
	// Sender Username.
	SenderUsername string `json:"sender_username"`
	// Receiver User ID.
	ReceiverID int `json:"receiver_id"`
	// Receiver Username.
	ReceiverUsername string `json:"receiver_username"`
	// Transaction amount (positive or negative).
	Amount      float64           `json:"amount"`
	Type        TransactionType   `json:"type"`
	Status      TransactionStatus `json:"status"`
	CreatedAt   time.Time         `json:"created_at"`
	CompletedAt OptNilDateTime    `json:"completed_at"`
}

// GetID returns the value of ID.
func (s *Transaction) GetID() TransactionID {
	return s.ID
}

// GetSenderID returns the value of SenderID.
func (s *Transaction) GetSenderID() int {
	return s.SenderID
}

// GetSenderUsername returns the value of SenderUsername.
func (s *Transaction) GetSenderUsername() string {
	return s.SenderUsername
}

// GetReceiverID returns the value of ReceiverID.
func (s *Transaction) GetReceiverID() int {
	return s.ReceiverID
}

// GetReceiverUsername returns the value of ReceiverUsername.
func (s *Transaction) GetReceiverUsername() string {
	return s.ReceiverUsername
}

// GetAmount returns the value of Amount.
func (s *Transaction) GetAmount() float64 {
	return s.Amount
}

// GetType returns the value of Type.
func (s *Transaction) GetType() TransactionType {
	return s.Type
}

// GetStatus returns the value of Status.
func (s *Transaction) GetStatus() TransactionStatus {
	return s.Status
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Transaction) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetCompletedAt returns the value of CompletedAt.
func (s *Transaction) GetCompletedAt() OptNilDateTime {
	return s.CompletedAt
}

// SetID sets the value of ID.
func (s *Transaction) SetID(val TransactionID) {
	s.ID = val
}

// SetSenderID sets the value of SenderID.
func (s *Transaction) SetSenderID(val int) {
	s.SenderID = val
}

// SetSenderUsername sets the value of SenderUsername.
func (s *Transaction) SetSenderUsername(val string) {
	s.SenderUsername = val
}

// SetReceiverID sets the value of ReceiverID.
func (s *Transaction) SetReceiverID(val int) {
	s.ReceiverID = val
}

// SetReceiverUsername sets the value of ReceiverUsername.
func (s *Transaction) SetReceiverUsername(val string) {
	s.ReceiverUsername = val
}

// SetAmount sets the value of Amount.
func (s *Transaction) SetAmount(val float64) {
	s.Amount = val
}

// SetType sets the value of Type.
func (s *Transaction) SetType(val TransactionType) {
	s.Type = val
}

// SetStatus sets the value of Status.
func (s *Transaction) SetStatus(val TransactionStatus) {
	s.Status = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Transaction) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetCompletedAt sets the value of CompletedAt.
func (s *Transaction) SetCompletedAt(val OptNilDateTime) {
	s.CompletedAt = val
}

func (*Transaction) createTransactionRes() {}

type TransactionID uuid.UUID

// Ref: #/components/schemas/TransactionPagination
type TransactionPagination struct {
	// Number of items returned.
	Limit int `json:"limit"`
	// Cursor for next page.
	NextCursor OptNilString `json:"next_cursor"`
	// Indicates if more results exist.
	HasMore bool `json:"has_more"`
}

// GetLimit returns the value of Limit.
func (s *TransactionPagination) GetLimit() int {
	return s.Limit
}

// GetNextCursor returns the value of NextCursor.
func (s *TransactionPagination) GetNextCursor() OptNilString {
	return s.NextCursor
}

// GetHasMore returns the value of HasMore.
func (s *TransactionPagination) GetHasMore() bool {
	return s.HasMore
}

// SetLimit sets the value of Limit.
func (s *TransactionPagination) SetLimit(val int) {
	s.Limit = val
}

// SetNextCursor sets the value of NextCursor.
func (s *TransactionPagination) SetNextCursor(val OptNilString) {
	s.NextCursor = val
}

// SetHasMore sets the value of HasMore.
func (s *TransactionPagination) SetHasMore(val bool) {
	s.HasMore = val
}

// Ref: #/components/schemas/TransactionStatus
type TransactionStatus string

const (
	TransactionStatusPending   TransactionStatus = "pending"
	TransactionStatusCompleted TransactionStatus = "completed"
	TransactionStatusRejected  TransactionStatus = "rejected"
	TransactionStatusCancelled TransactionStatus = "cancelled"
)

// AllValues returns all TransactionStatus values.
func (TransactionStatus) AllValues() []TransactionStatus {
	return []TransactionStatus{
		TransactionStatusPending,
		TransactionStatusCompleted,
		TransactionStatusRejected,
		TransactionStatusCancelled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TransactionStatus) MarshalText() ([]byte, error) {
	switch s {
	case TransactionStatusPending:
		return []byte(s), nil
	case TransactionStatusCompleted:
		return []byte(s), nil
	case TransactionStatusRejected:
		return []byte(s), nil
	case TransactionStatusCancelled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TransactionStatus) UnmarshalText(data []byte) error {
	switch TransactionStatus(data) {
	case TransactionStatusPending:
		*s = TransactionStatusPending
		return nil
	case TransactionStatusCompleted:
		*s = TransactionStatusCompleted
		return nil
	case TransactionStatusRejected:
		*s = TransactionStatusRejected
		return nil
	case TransactionStatusCancelled:
		*s = TransactionStatusCancelled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type TransactionType string

const (
	TransactionTypeSend    TransactionType = "send"
	TransactionTypeRequest TransactionType = "request"
	TransactionTypeRefund  TransactionType = "refund"
)

// AllValues returns all TransactionType values.
func (TransactionType) AllValues() []TransactionType {
	return []TransactionType{
		TransactionTypeSend,
		TransactionTypeRequest,
		TransactionTypeRefund,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TransactionType) MarshalText() ([]byte, error) {
	switch s {
	case TransactionTypeSend:
		return []byte(s), nil
	case TransactionTypeRequest:
		return []byte(s), nil
	case TransactionTypeRefund:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TransactionType) UnmarshalText(data []byte) error {
	switch TransactionType(data) {
	case TransactionTypeSend:
		*s = TransactionTypeSend
		return nil
	case TransactionTypeRequest:
		*s = TransactionTypeRequest
		return nil
	case TransactionTypeRefund:
		*s = TransactionTypeRefund
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Transactions
type Transactions struct {
	// User ID.
	ID           int                   `json:"id"`
	Transactions []Transaction         `json:"transactions"`
	Pagination   TransactionPagination `json:"pagination"`
}

// GetID returns the value of ID.
func (s *Transactions) GetID() int {
	return s.ID
}

// GetTransactions returns the value of Transactions.
func (s *Transactions) GetTransactions() []Transaction {
	return s.Transactions
}

// GetPagination returns the value of Pagination.
func (s *Transactions) GetPagination() TransactionPagination {
	return s.Pagination
}

// SetID sets the value of ID.
func (s *Transactions) SetID(val int) {
	s.ID = val
}

// SetTransactions sets the value of Transactions.
func (s *Transactions) SetTransactions(val []Transaction) {
	s.Transactions = val
}

// SetPagination sets the value of Pagination.
func (s *Transactions) SetPagination(val TransactionPagination) {
	s.Pagination = val
}

func (*Transactions) getTransactionsRes() {}

type UpdateDiscordUserAutofillByIdBadRequest Error

func (*UpdateDiscordUserAutofillByIdBadRequest) updateDiscordUserAutofillByIdRes() {}

type UpdateDiscordUserAutofillByIdInternalServerError Error

func (*UpdateDiscordUserAutofillByIdInternalServerError) updateDiscordUserAutofillByIdRes() {}

type UpdateDiscordUserAutofillByIdNotFound Error

func (*UpdateDiscordUserAutofillByIdNotFound) updateDiscordUserAutofillByIdRes() {}

type UpdateDiscordUserLanguageByIdBadRequest Error

func (*UpdateDiscordUserLanguageByIdBadRequest) updateDiscordUserLanguageByIdRes() {}

type UpdateDiscordUserLanguageByIdInternalServerError Error

func (*UpdateDiscordUserLanguageByIdInternalServerError) updateDiscordUserLanguageByIdRes() {}

type UpdateDiscordUserLanguageByIdNotFound Error

func (*UpdateDiscordUserLanguageByIdNotFound) updateDiscordUserLanguageByIdRes() {}

type UpdateUserBalanceByIdBadRequest Error

func (*UpdateUserBalanceByIdBadRequest) updateUserBalanceByIdRes() {}

type UpdateUserBalanceByIdForbidden Error

func (*UpdateUserBalanceByIdForbidden) updateUserBalanceByIdRes() {}

type UpdateUserBalanceByIdInternalServerError Error

func (*UpdateUserBalanceByIdInternalServerError) updateUserBalanceByIdRes() {}

type UpdateUserBalanceByIdNotFound Error

func (*UpdateUserBalanceByIdNotFound) updateUserBalanceByIdRes() {}

type UpdateUserBalanceByIdUnauthorized Error

func (*UpdateUserBalanceByIdUnauthorized) updateUserBalanceByIdRes() {}

// Merged schema.
// Ref: #/components/schemas/User
type User struct {
	ID       int    `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
}

// GetID returns the value of ID.
func (s *User) GetID() int {
	return s.ID
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() string {
	return s.Email
}

// GetUsername returns the value of Username.
func (s *User) GetUsername() string {
	return s.Username
}

// SetID sets the value of ID.
func (s *User) SetID(val int) {
	s.ID = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val string) {
	s.Email = val
}

// SetUsername sets the value of Username.
func (s *User) SetUsername(val string) {
	s.Username = val
}

func (*User) createUserRes()  {}
func (*User) getUserByIdRes() {}
