// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/Balance
type Balance struct {
	Balance int64 `json:"balance"`
}

// GetBalance returns the value of Balance.
func (s *Balance) GetBalance() int64 {
	return s.Balance
}

// SetBalance sets the value of Balance.
func (s *Balance) SetBalance(val int64) {
	s.Balance = val
}

func (*Balance) getUserBalanceByIdRes()    {}
func (*Balance) updateUserBalanceByIdRes() {}

type CreateDiscordUserBadRequest Error

func (*CreateDiscordUserBadRequest) createDiscordUserRes() {}

type CreateDiscordUserConflict Error

func (*CreateDiscordUserConflict) createDiscordUserRes() {}

// Merged schema.
// Ref: #/components/schemas/CreateDiscordUserData
type CreateDiscordUserData struct {
	DiscordId string `json:"discordId"`
	Password  string `json:"password"`
}

// GetDiscordId returns the value of DiscordId.
func (s *CreateDiscordUserData) GetDiscordId() string {
	return s.DiscordId
}

// GetPassword returns the value of Password.
func (s *CreateDiscordUserData) GetPassword() string {
	return s.Password
}

// SetDiscordId sets the value of DiscordId.
func (s *CreateDiscordUserData) SetDiscordId(val string) {
	s.DiscordId = val
}

// SetPassword sets the value of Password.
func (s *CreateDiscordUserData) SetPassword(val string) {
	s.Password = val
}

type CreateDiscordUserInternalServerError Error

func (*CreateDiscordUserInternalServerError) createDiscordUserRes() {}

type CreateLinkAccountCodeBadRequest Error

func (*CreateLinkAccountCodeBadRequest) createLinkAccountCodeRes() {}

type CreateLinkAccountCodeInternalServerError Error

func (*CreateLinkAccountCodeInternalServerError) createLinkAccountCodeRes() {}

type CreateLinkAccountCodeNotFound Error

func (*CreateLinkAccountCodeNotFound) createLinkAccountCodeRes() {}

type CreateUserBadRequest Error

func (*CreateUserBadRequest) createUserRes() {}

type CreateUserConflict Error

func (*CreateUserConflict) createUserRes() {}

// Merged schema.
// Ref: #/components/schemas/CreateUserData
type CreateUserData struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	// User password.
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *CreateUserData) GetEmail() string {
	return s.Email
}

// GetUsername returns the value of Username.
func (s *CreateUserData) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *CreateUserData) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *CreateUserData) SetEmail(val string) {
	s.Email = val
}

// SetUsername sets the value of Username.
func (s *CreateUserData) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *CreateUserData) SetPassword(val string) {
	s.Password = val
}

type CreateUserInternalServerError Error

func (*CreateUserInternalServerError) createUserRes() {}

// Merged schema.
// Ref: #/components/schemas/DiscordUser
type DiscordUser struct {
	ID        int    `json:"id"`
	DiscordId string `json:"discordId"`
}

// GetID returns the value of ID.
func (s *DiscordUser) GetID() int {
	return s.ID
}

// GetDiscordId returns the value of DiscordId.
func (s *DiscordUser) GetDiscordId() string {
	return s.DiscordId
}

// SetID sets the value of ID.
func (s *DiscordUser) SetID(val int) {
	s.ID = val
}

// SetDiscordId sets the value of DiscordId.
func (s *DiscordUser) SetDiscordId(val string) {
	s.DiscordId = val
}

func (*DiscordUser) createDiscordUserRes() {}

// Ref: #/components/schemas/DiscordUserAutofill
type DiscordUserAutofill struct {
	Autofill int `json:"autofill"`
}

// GetAutofill returns the value of Autofill.
func (s *DiscordUserAutofill) GetAutofill() int {
	return s.Autofill
}

// SetAutofill sets the value of Autofill.
func (s *DiscordUserAutofill) SetAutofill(val int) {
	s.Autofill = val
}

func (*DiscordUserAutofill) getDiscordUserAutofillByIdRes()    {}
func (*DiscordUserAutofill) updateDiscordUserAutofillByIdRes() {}

// Ref: #/components/schemas/DiscordUserLanguage
type DiscordUserLanguage struct {
	Language string `json:"language"`
}

// GetLanguage returns the value of Language.
func (s *DiscordUserLanguage) GetLanguage() string {
	return s.Language
}

// SetLanguage sets the value of Language.
func (s *DiscordUserLanguage) SetLanguage(val string) {
	s.Language = val
}

func (*DiscordUserLanguage) getDiscordUserLanguageByIdRes()    {}
func (*DiscordUserLanguage) updateDiscordUserLanguageByIdRes() {}

// Ref: #/components/schemas/DiscordUserLoginData
type DiscordUserLoginData struct {
	DiscordId string `json:"discordId"`
	Password  string `json:"password"`
}

// GetDiscordId returns the value of DiscordId.
func (s *DiscordUserLoginData) GetDiscordId() string {
	return s.DiscordId
}

// GetPassword returns the value of Password.
func (s *DiscordUserLoginData) GetPassword() string {
	return s.Password
}

// SetDiscordId sets the value of DiscordId.
func (s *DiscordUserLoginData) SetDiscordId(val string) {
	s.DiscordId = val
}

// SetPassword sets the value of Password.
func (s *DiscordUserLoginData) SetPassword(val string) {
	s.Password = val
}

// Merged schema.
// Ref: #/components/schemas/DiscordUserSessionData
type DiscordUserSessionData struct {
	DiscordId string `json:"discordId"`
	Autofill  int    `json:"autofill"`
	Language  string `json:"language"`
}

// GetDiscordId returns the value of DiscordId.
func (s *DiscordUserSessionData) GetDiscordId() string {
	return s.DiscordId
}

// GetAutofill returns the value of Autofill.
func (s *DiscordUserSessionData) GetAutofill() int {
	return s.Autofill
}

// GetLanguage returns the value of Language.
func (s *DiscordUserSessionData) GetLanguage() string {
	return s.Language
}

// SetDiscordId sets the value of DiscordId.
func (s *DiscordUserSessionData) SetDiscordId(val string) {
	s.DiscordId = val
}

// SetAutofill sets the value of Autofill.
func (s *DiscordUserSessionData) SetAutofill(val int) {
	s.Autofill = val
}

// SetLanguage sets the value of Language.
func (s *DiscordUserSessionData) SetLanguage(val string) {
	s.Language = val
}

func (*DiscordUserSessionData) loginDiscordUserRes() {}

// Ref: #/components/schemas/ErrorService
type Error struct {
	Message OptString `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() OptString {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val OptString) {
	s.Message = val
}

type GetAccountLinkByIdBadRequest Error

func (*GetAccountLinkByIdBadRequest) getAccountLinkByIdRes() {}

type GetAccountLinkByIdConflict Error

func (*GetAccountLinkByIdConflict) getAccountLinkByIdRes() {}

type GetAccountLinkByIdInternalServerError Error

func (*GetAccountLinkByIdInternalServerError) getAccountLinkByIdRes() {}

type GetAccountLinkByIdNotFound Error

func (*GetAccountLinkByIdNotFound) getAccountLinkByIdRes() {}

type GetDiscordUserAutofillByIdBadRequest Error

func (*GetDiscordUserAutofillByIdBadRequest) getDiscordUserAutofillByIdRes() {}

type GetDiscordUserAutofillByIdInternalServerError Error

func (*GetDiscordUserAutofillByIdInternalServerError) getDiscordUserAutofillByIdRes() {}

type GetDiscordUserAutofillByIdNotFound Error

func (*GetDiscordUserAutofillByIdNotFound) getDiscordUserAutofillByIdRes() {}

type GetDiscordUserLanguageByIdBadRequest Error

func (*GetDiscordUserLanguageByIdBadRequest) getDiscordUserLanguageByIdRes() {}

type GetDiscordUserLanguageByIdInternalServerError Error

func (*GetDiscordUserLanguageByIdInternalServerError) getDiscordUserLanguageByIdRes() {}

type GetDiscordUserLanguageByIdNotFound Error

func (*GetDiscordUserLanguageByIdNotFound) getDiscordUserLanguageByIdRes() {}

type GetUserBalanceByIdBadRequest Error

func (*GetUserBalanceByIdBadRequest) getUserBalanceByIdRes() {}

type GetUserBalanceByIdForbidden Error

func (*GetUserBalanceByIdForbidden) getUserBalanceByIdRes() {}

type GetUserBalanceByIdInternalServerError Error

func (*GetUserBalanceByIdInternalServerError) getUserBalanceByIdRes() {}

type GetUserBalanceByIdNotFound Error

func (*GetUserBalanceByIdNotFound) getUserBalanceByIdRes() {}

type GetUserBalanceByIdUnauthorized Error

func (*GetUserBalanceByIdUnauthorized) getUserBalanceByIdRes() {}

type GetUserByIdBadRequest Error

func (*GetUserByIdBadRequest) getUserByIdRes() {}

type GetUserByIdForbidden Error

func (*GetUserByIdForbidden) getUserByIdRes() {}

type GetUserByIdInternalServerError Error

func (*GetUserByIdInternalServerError) getUserByIdRes() {}

type GetUserByIdNotFound Error

func (*GetUserByIdNotFound) getUserByIdRes() {}

type GetUserByIdUnauthorized Error

func (*GetUserByIdUnauthorized) getUserByIdRes() {}

type LinkAccountBadRequest Error

func (*LinkAccountBadRequest) linkAccountRes() {}

type LinkAccountConflict Error

func (*LinkAccountConflict) linkAccountRes() {}

type LinkAccountInternalServerError Error

func (*LinkAccountInternalServerError) linkAccountRes() {}

type LinkAccountNotFound Error

func (*LinkAccountNotFound) linkAccountRes() {}

// Ref: #/components/schemas/LinkCode
type LinkCode struct {
	Code string `json:"code"`
}

// GetCode returns the value of Code.
func (s *LinkCode) GetCode() string {
	return s.Code
}

// SetCode sets the value of Code.
func (s *LinkCode) SetCode(val string) {
	s.Code = val
}

func (*LinkCode) createLinkAccountCodeRes() {}

// Ref: #/components/schemas/LinkedAccountID
type LinkedAccountID struct {
	ID int `json:"id"`
}

// GetID returns the value of ID.
func (s *LinkedAccountID) GetID() int {
	return s.ID
}

// SetID sets the value of ID.
func (s *LinkedAccountID) SetID(val int) {
	s.ID = val
}

func (*LinkedAccountID) getAccountLinkByIdRes() {}
func (*LinkedAccountID) linkAccountRes()        {}

// Ref: #/components/schemas/LoginData
type LoginData struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *LoginData) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *LoginData) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *LoginData) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *LoginData) SetPassword(val string) {
	s.Password = val
}

type LoginDiscordUserBadRequest Error

func (*LoginDiscordUserBadRequest) loginDiscordUserRes() {}

type LoginDiscordUserInternalServerError Error

func (*LoginDiscordUserInternalServerError) loginDiscordUserRes() {}

type LoginDiscordUserNotFound Error

func (*LoginDiscordUserNotFound) loginDiscordUserRes() {}

type LoginDiscordUserUnauthorized Error

func (*LoginDiscordUserUnauthorized) loginDiscordUserRes() {}

type LoginUserBadRequest Error

func (*LoginUserBadRequest) loginUserRes() {}

type LoginUserInternalServerError Error

func (*LoginUserInternalServerError) loginUserRes() {}

type LoginUserNotFound Error

func (*LoginUserNotFound) loginUserRes() {}

type LoginUserUnauthorized Error

func (*LoginUserUnauthorized) loginUserRes() {}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Token
type Token struct {
	Token string `json:"token"`
}

// GetToken returns the value of Token.
func (s *Token) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *Token) SetToken(val string) {
	s.Token = val
}

func (*Token) loginUserRes() {}

type UpdateDiscordUserAutofillByIdBadRequest Error

func (*UpdateDiscordUserAutofillByIdBadRequest) updateDiscordUserAutofillByIdRes() {}

type UpdateDiscordUserAutofillByIdInternalServerError Error

func (*UpdateDiscordUserAutofillByIdInternalServerError) updateDiscordUserAutofillByIdRes() {}

type UpdateDiscordUserAutofillByIdNotFound Error

func (*UpdateDiscordUserAutofillByIdNotFound) updateDiscordUserAutofillByIdRes() {}

type UpdateDiscordUserLanguageByIdBadRequest Error

func (*UpdateDiscordUserLanguageByIdBadRequest) updateDiscordUserLanguageByIdRes() {}

type UpdateDiscordUserLanguageByIdInternalServerError Error

func (*UpdateDiscordUserLanguageByIdInternalServerError) updateDiscordUserLanguageByIdRes() {}

type UpdateDiscordUserLanguageByIdNotFound Error

func (*UpdateDiscordUserLanguageByIdNotFound) updateDiscordUserLanguageByIdRes() {}

type UpdateUserBalanceByIdBadRequest Error

func (*UpdateUserBalanceByIdBadRequest) updateUserBalanceByIdRes() {}

type UpdateUserBalanceByIdForbidden Error

func (*UpdateUserBalanceByIdForbidden) updateUserBalanceByIdRes() {}

type UpdateUserBalanceByIdInternalServerError Error

func (*UpdateUserBalanceByIdInternalServerError) updateUserBalanceByIdRes() {}

type UpdateUserBalanceByIdNotFound Error

func (*UpdateUserBalanceByIdNotFound) updateUserBalanceByIdRes() {}

type UpdateUserBalanceByIdUnauthorized Error

func (*UpdateUserBalanceByIdUnauthorized) updateUserBalanceByIdRes() {}

// Merged schema.
// Ref: #/components/schemas/User
type User struct {
	ID       int    `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
}

// GetID returns the value of ID.
func (s *User) GetID() int {
	return s.ID
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() string {
	return s.Email
}

// GetUsername returns the value of Username.
func (s *User) GetUsername() string {
	return s.Username
}

// SetID sets the value of ID.
func (s *User) SetID(val int) {
	s.ID = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val string) {
	s.Email = val
}

// SetUsername sets the value of Username.
func (s *User) SetUsername(val string) {
	s.Username = val
}

func (*User) createUserRes()  {}
func (*User) getUserByIdRes() {}
