// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AcceptTransactionOperation             OperationName = "AcceptTransaction"
	CancelTransactionOperation             OperationName = "CancelTransaction"
	ClaimDailyBalanceOperation             OperationName = "ClaimDailyBalance"
	CreateDiscordUserOperation             OperationName = "CreateDiscordUser"
	CreateLinkAccountCodeOperation         OperationName = "CreateLinkAccountCode"
	CreateTransactionOperation             OperationName = "CreateTransaction"
	CreateUserOperation                    OperationName = "CreateUser"
	GetAccountLinkByIdOperation            OperationName = "GetAccountLinkById"
	GetDailyClaimStatusOperation           OperationName = "GetDailyClaimStatus"
	GetDiscordUserAutofillByIdOperation    OperationName = "GetDiscordUserAutofillById"
	GetDiscordUserLanguageByIdOperation    OperationName = "GetDiscordUserLanguageById"
	GetTransactionsOperation               OperationName = "GetTransactions"
	GetUserBalanceByIdOperation            OperationName = "GetUserBalanceById"
	GetUserByIdOperation                   OperationName = "GetUserById"
	LinkAccountOperation                   OperationName = "LinkAccount"
	LoginDiscordUserOperation              OperationName = "LoginDiscordUser"
	LoginUserOperation                     OperationName = "LoginUser"
	RefundTransactionOperation             OperationName = "RefundTransaction"
	RejectTransactionOperation             OperationName = "RejectTransaction"
	UpdateDiscordUserAutofillByIdOperation OperationName = "UpdateDiscordUserAutofillById"
	UpdateDiscordUserLanguageByIdOperation OperationName = "UpdateDiscordUserLanguageById"
	UpdateUserBalanceByIdOperation         OperationName = "UpdateUserBalanceById"
)
