// Code generated by ogen, DO NOT EDIT.
package api

type CreateDiscordUserRes interface {
	createDiscordUserRes()
}

type CreateLinkAccountCodeRes interface {
	createLinkAccountCodeRes()
}

type CreateUserRes interface {
	createUserRes()
}

type GetAccountLinkByIdRes interface {
	getAccountLinkByIdRes()
}

type GetDiscordUserAutofillByIdRes interface {
	getDiscordUserAutofillByIdRes()
}

type GetDiscordUserLanguageByIdRes interface {
	getDiscordUserLanguageByIdRes()
}

type GetUserBalanceByIdRes interface {
	getUserBalanceByIdRes()
}

type GetUserByIdRes interface {
	getUserByIdRes()
}

type LinkAccountRes interface {
	linkAccountRes()
}

type LoginDiscordUserRes interface {
	loginDiscordUserRes()
}

type LoginUserRes interface {
	loginUserRes()
}

type UpdateDiscordUserAutofillByIdRes interface {
	updateDiscordUserAutofillByIdRes()
}

type UpdateDiscordUserLanguageByIdRes interface {
	updateDiscordUserLanguageByIdRes()
}

type UpdateUserBalanceByIdRes interface {
	updateUserBalanceByIdRes()
}
