// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateDiscordUserOperation             OperationName = "CreateDiscordUser"
	CreateLinkAccountCodeOperation         OperationName = "CreateLinkAccountCode"
	CreateUserOperation                    OperationName = "CreateUser"
	GetAccountLinkByIdOperation            OperationName = "GetAccountLinkById"
	GetDiscordUserAutofillByIdOperation    OperationName = "GetDiscordUserAutofillById"
	GetDiscordUserLanguageByIdOperation    OperationName = "GetDiscordUserLanguageById"
	GetUserBalanceByIdOperation            OperationName = "GetUserBalanceById"
	GetUserByIdOperation                   OperationName = "GetUserById"
	LinkAccountOperation                   OperationName = "LinkAccount"
	LoginDiscordUserOperation              OperationName = "LoginDiscordUser"
	LoginUserOperation                     OperationName = "LoginUser"
	UpdateDiscordUserAutofillByIdOperation OperationName = "UpdateDiscordUserAutofillById"
	UpdateDiscordUserLanguageByIdOperation OperationName = "UpdateDiscordUserLanguageById"
	UpdateUserBalanceByIdOperation         OperationName = "UpdateUserBalanceById"
)
