// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	DiscordUsersHandler
	LoginHandler
	UsersHandler
}

// DiscordUsersHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: DiscordUsers
type DiscordUsersHandler interface {
	// CreateDiscordUser implements createDiscordUser operation.
	//
	// Create a new Discord User.
	//
	// POST /discord-users
	CreateDiscordUser(ctx context.Context, req *CreateDiscordUserData) (CreateDiscordUserRes, error)
	// GetAccountLinkById implements getAccountLinkById operation.
	//
	// Get Discord User Account Link By Id.
	//
	// GET /discord-users/link-account/{id}
	GetAccountLinkById(ctx context.Context, params GetAccountLinkByIdParams) (GetAccountLinkByIdRes, error)
	// GetDiscordUserAutofillById implements getDiscordUserAutofillById operation.
	//
	// Gets Autofill By DiscordId.
	//
	// GET /discord-users/autofill/{id}
	GetDiscordUserAutofillById(ctx context.Context, params GetDiscordUserAutofillByIdParams) (GetDiscordUserAutofillByIdRes, error)
	// GetDiscordUserLanguageById implements getDiscordUserLanguageById operation.
	//
	// Get Discord User Language By Id.
	//
	// GET /discord-users/language/{id}
	GetDiscordUserLanguageById(ctx context.Context, params GetDiscordUserLanguageByIdParams) (GetDiscordUserLanguageByIdRes, error)
	// LinkAccount implements linkAccount operation.
	//
	// Create Account Link for Discord.
	//
	// POST /discord-users/link-account/{id}
	LinkAccount(ctx context.Context, req *LinkCode, params LinkAccountParams) (LinkAccountRes, error)
	// LoginDiscordUser implements loginDiscordUser operation.
	//
	// POST /discord-users/login
	LoginDiscordUser(ctx context.Context, req *DiscordUserLoginData) (LoginDiscordUserRes, error)
	// UpdateDiscordUserAutofillById implements updateDiscordUserAutofillById operation.
	//
	// Updates Discord User Autofill Config.
	//
	// PUT /discord-users/autofill/{id}
	UpdateDiscordUserAutofillById(ctx context.Context, params UpdateDiscordUserAutofillByIdParams) (UpdateDiscordUserAutofillByIdRes, error)
	// UpdateDiscordUserLanguageById implements updateDiscordUserLanguageById operation.
	//
	// Update Discord User Language By Id.
	//
	// PUT /discord-users/language/{id}
	UpdateDiscordUserLanguageById(ctx context.Context, req *DiscordUserLanguage, params UpdateDiscordUserLanguageByIdParams) (UpdateDiscordUserLanguageByIdRes, error)
}

// LoginHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Login
type LoginHandler interface {
	// LoginUser implements loginUser operation.
	//
	// Login User.
	//
	// POST /login
	LoginUser(ctx context.Context, req *LoginData) (LoginUserRes, error)
}

// UsersHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Users
type UsersHandler interface {
	// CreateLinkAccountCode implements createLinkAccountCode operation.
	//
	// Link User Account with Discord User.
	//
	// POST /users/link-account-code/{id}
	CreateLinkAccountCode(ctx context.Context, params CreateLinkAccountCodeParams) (CreateLinkAccountCodeRes, error)
	// CreateUser implements createUser operation.
	//
	// Create a new user.
	//
	// POST /users
	CreateUser(ctx context.Context, req *CreateUserData) (CreateUserRes, error)
	// GetUserBalanceById implements getUserBalanceById operation.
	//
	// Get User Balance By Id.
	//
	// GET /users/balance/{id}
	GetUserBalanceById(ctx context.Context, params GetUserBalanceByIdParams) (GetUserBalanceByIdRes, error)
	// GetUserById implements getUserById operation.
	//
	// Get a user by id.
	//
	// GET /users/{id}
	GetUserById(ctx context.Context, params GetUserByIdParams) (GetUserByIdRes, error)
	// UpdateUserBalanceById implements updateUserBalanceById operation.
	//
	// Update a User Balance.
	//
	// PUT /users/balance/{id}
	UpdateUserBalanceById(ctx context.Context, req *Balance, params UpdateUserBalanceByIdParams) (UpdateUserBalanceByIdRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
