// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AcceptTransaction implements acceptTransaction operation.
//
// Accept a Transaction.
//
// POST /transactions/{id}/accept
func (UnimplementedHandler) AcceptTransaction(ctx context.Context, params AcceptTransactionParams) (r AcceptTransactionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CancelTransaction implements cancelTransaction operation.
//
// Cancel a Transaction.
//
// POST /transactions/{id}/cancel
func (UnimplementedHandler) CancelTransaction(ctx context.Context, params CancelTransactionParams) (r CancelTransactionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDiscordUser implements createDiscordUser operation.
//
// Create a new Discord User.
//
// POST /discord-users
func (UnimplementedHandler) CreateDiscordUser(ctx context.Context, req *CreateDiscordUserData) (r CreateDiscordUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateLinkAccountCode implements createLinkAccountCode operation.
//
// Link User Account with Discord User.
//
// POST /users/link-account-code/{id}
func (UnimplementedHandler) CreateLinkAccountCode(ctx context.Context, params CreateLinkAccountCodeParams) (r CreateLinkAccountCodeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTransaction implements createTransaction operation.
//
// Creates A New Transaction.
//
// POST /transactions
func (UnimplementedHandler) CreateTransaction(ctx context.Context, req *CreateTransaction) (r CreateTransactionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUser implements createUser operation.
//
// Create a new user.
//
// POST /users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *CreateUserData) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAccountLinkById implements getAccountLinkById operation.
//
// Get Discord User Account Link By Id.
//
// GET /discord-users/link-account/{id}
func (UnimplementedHandler) GetAccountLinkById(ctx context.Context, params GetAccountLinkByIdParams) (r GetAccountLinkByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDiscordUserAutofillById implements getDiscordUserAutofillById operation.
//
// Gets Autofill By DiscordId.
//
// GET /discord-users/autofill/{id}
func (UnimplementedHandler) GetDiscordUserAutofillById(ctx context.Context, params GetDiscordUserAutofillByIdParams) (r GetDiscordUserAutofillByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDiscordUserLanguageById implements getDiscordUserLanguageById operation.
//
// Get Discord User Language By Id.
//
// GET /discord-users/language/{id}
func (UnimplementedHandler) GetDiscordUserLanguageById(ctx context.Context, params GetDiscordUserLanguageByIdParams) (r GetDiscordUserLanguageByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIdByUsername implements getIdByUsername operation.
//
// Get id by username.
//
// GET /users
func (UnimplementedHandler) GetIdByUsername(ctx context.Context, params GetIdByUsernameParams) (r GetIdByUsernameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTransactions implements getTransactions operation.
//
// Returns a paginated list of transactions for a user.
//
// GET /transactions/{id}
func (UnimplementedHandler) GetTransactions(ctx context.Context, params GetTransactionsParams) (r GetTransactionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserBalanceById implements getUserBalanceById operation.
//
// Get User Balance By Id.
//
// GET /users/balance/{id}
func (UnimplementedHandler) GetUserBalanceById(ctx context.Context, params GetUserBalanceByIdParams) (r GetUserBalanceByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserById implements getUserById operation.
//
// Get a user by id.
//
// GET /users/{id}
func (UnimplementedHandler) GetUserById(ctx context.Context, params GetUserByIdParams) (r GetUserByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LinkAccount implements linkAccount operation.
//
// Create Account Link for Discord.
//
// POST /discord-users/link-account/{id}
func (UnimplementedHandler) LinkAccount(ctx context.Context, req *LinkCode, params LinkAccountParams) (r LinkAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginDiscordUser implements loginDiscordUser operation.
//
// POST /discord-users/login
func (UnimplementedHandler) LoginDiscordUser(ctx context.Context, req *DiscordUserLoginData) (r LoginDiscordUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginUser implements loginUser operation.
//
// Login User.
//
// POST /login
func (UnimplementedHandler) LoginUser(ctx context.Context, req *LoginData) (r LoginUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RejectTransaction implements rejectTransaction operation.
//
// Reject a Transaction.
//
// POST /transactions/{id}/reject
func (UnimplementedHandler) RejectTransaction(ctx context.Context, params RejectTransactionParams) (r RejectTransactionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDiscordUserAutofillById implements updateDiscordUserAutofillById operation.
//
// Updates Discord User Autofill Config.
//
// PUT /discord-users/autofill/{id}
func (UnimplementedHandler) UpdateDiscordUserAutofillById(ctx context.Context, params UpdateDiscordUserAutofillByIdParams) (r UpdateDiscordUserAutofillByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDiscordUserLanguageById implements updateDiscordUserLanguageById operation.
//
// Update Discord User Language By Id.
//
// PUT /discord-users/language/{id}
func (UnimplementedHandler) UpdateDiscordUserLanguageById(ctx context.Context, req *DiscordUserLanguage, params UpdateDiscordUserLanguageByIdParams) (r UpdateDiscordUserLanguageByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUserBalanceById implements updateUserBalanceById operation.
//
// Update a User Balance.
//
// PUT /users/balance/{id}
func (UnimplementedHandler) UpdateUserBalanceById(ctx context.Context, req *Balance, params UpdateUserBalanceByIdParams) (r UpdateUserBalanceByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}
