// Code generated by ogen, DO NOT EDIT.
package api

type AcceptTransactionRes interface {
	acceptTransactionRes()
}

type CancelTransactionRes interface {
	cancelTransactionRes()
}

type CashoutCasinoBalanceRes interface {
	cashoutCasinoBalanceRes()
}

type ClaimDailyBalanceRes interface {
	claimDailyBalanceRes()
}

type CreateBetRollADiceRes interface {
	createBetRollADiceRes()
}

type CreateDiscordUserRes interface {
	createDiscordUserRes()
}

type CreateLinkAccountCodeRes interface {
	createLinkAccountCodeRes()
}

type CreateTransactionRes interface {
	createTransactionRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DepositCasinoBalanceRes interface {
	depositCasinoBalanceRes()
}

type GetAccountLinkByIdRes interface {
	getAccountLinkByIdRes()
}

type GetCasinoBalanceRes interface {
	getCasinoBalanceRes()
}

type GetDailyClaimStatusRes interface {
	getDailyClaimStatusRes()
}

type GetDiscordUserAutofillByIdRes interface {
	getDiscordUserAutofillByIdRes()
}

type GetDiscordUserLanguageByIdRes interface {
	getDiscordUserLanguageByIdRes()
}

type GetTransactionsRes interface {
	getTransactionsRes()
}

type GetUserBalanceByIdRes interface {
	getUserBalanceByIdRes()
}

type GetUserByIdRes interface {
	getUserByIdRes()
}

type LinkAccountRes interface {
	linkAccountRes()
}

type LoginDiscordUserRes interface {
	loginDiscordUserRes()
}

type LoginUserRes interface {
	loginUserRes()
}

type RefundTransactionRes interface {
	refundTransactionRes()
}

type RejectTransactionRes interface {
	rejectTransactionRes()
}

type UpdateCasinoBalanceRes interface {
	updateCasinoBalanceRes()
}

type UpdateDiscordUserAutofillByIdRes interface {
	updateDiscordUserAutofillByIdRes()
}

type UpdateDiscordUserLanguageByIdRes interface {
	updateDiscordUserLanguageByIdRes()
}

type UpdateUserBalanceByIdRes interface {
	updateUserBalanceByIdRes()
}
