services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ecoplatform
      MYSQL_USER: ecoplatform
      MYSQL_PASSWORD: 1
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      timeout: 5s

  migrate:
    image: flyway/flyway:latest
    depends_on:
      - db
    volumes:
      - ./backend/migrations:/flyway/mysql
    command: >
      -url=jdbc:mysql://db:3306/ecoplatform
      -user=ecoplatform
      -password=1
      -locations=filesystem:/flyway/mysql
      -connectRetries=10
      migrate

  backend:
    build: ./backend
    container_name: api
    restart: always
    env_file:
      - backend/.env
    environment:
      DSN: ecoplatform:1@tcp(db:3306)/ecoplatform?parseTime=true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  bot:
    build: ./bot
    container_name: bot
    restart: always
    profiles: ["bot"]
    env_file:
      - ./bot/.env
    depends_on:
      - backend

volumes:
  mysqldata: