-- Users
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  discord_id VARCHAR(50) UNIQUE NOT NULL,
  balance NUMERIC(20,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Stocks
CREATE TABLE IF NOT EXISTS stocks (
  id SERIAL PRIMARY KEY,
  symbol VARCHAR(10) UNIQUE NOT NULL,
  name VARCHAR(50) NOT NULL,
  category VARCHAR(50) NOT NULL,
  current_price NUMERIC(20,2) NOT NULL,
  shares NUMERIC(20, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Stock History
CREATE TABLE IF NOT EXISTS stock_history (
  id SERIAL PRIMARY KEY,
  stock_id INT REFERENCES stocks(id) ON DELETE CASCADE,
  price NUMERIC(20,2) NOT NULL,
  shares NUMERIC(20, 2) NOT NULL,
  timestamp TIMESTAMP DEFAULT NOW()
);
