CREATE TABLE IF NOT EXISTS users (
     id INT AUTO_INCREMENT PRIMARY KEY,
     discord_id VARCHAR(255) UNIQUE,
     username VARCHAR(255) UNIQUE,
     balance DOUBLE DEFAULT 0,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);